server {
    listen 80;
    root /usr/share/nginx/html;
    location / { try_files $uri /index.html; }
    location /api/ {
        proxy_pass http://api:8100;
        proxy_set_header Host localhost;
        client_max_body_size 40k;
    }
}
